apiVersion:  networking.k8s.io/v1
kind:  Ingress
metadata:
  name:  ingress-deletetasks 
  labels:
    app:  deletetasks
spec:  
  ingressClassName:  azure-application-gateway
  rules:
  - host: deletetask.techno028.shop
    http:
     paths:
      - pathType: Prefix
        path: "/"
        backend:
         service:
           name:  todo-delete-tasks-api
           port: 
            number:  80
       path: /
       pathType:  Prefix
